name: Avalon
version: 1.0-SNAPSHOT
main: id.avalon.AvalonPlugin
api-version: '1.21'
description: The Resistance Avalon Minecraft Plugin

commands:
  regis:
    description: Register player ke game Avalon
    usage: /regis <playername>
    permission: avalon.admin
  unregis:
    description: Unregister player dari game Avalon
    usage: /unregis <playername>
    permission: avalon.admin
  listplayer:
    description: List registered players
    usage: /listplayer
    permission: avalon.admin
  customrole:
    description: Custom role Avalon
    usage: /customrole
    permission: avalon.admin
  cutscene:
    description: Toggle cutscene on/off
    usage: /cutscene <on|off>
    permission: avalon.admin
  roleinfo:
    description: Menampilkan informasi role Avalon
    usage: /roleinfo <role>
  startgame:
    description: Mulai permainan Avalon
    usage: /startgame
    permission: avalon.admin
  debugroles:
    description: Debug role
    usage: /debugroles
    permission: avalon.admin
  stopgame:
    description: Hentikan game tanpa unregister player
    usage: /stopgame
    permission: avalon.admin
  settimer:
    description: Set timer
    usage: /settimer <type> <seconds>
    permission: avalon.admin

permissions:
  avalon.admin:
    description: Admin permission untuk Avalon
    default: op